version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: openjdk:8
    steps:
      - checkout
      - run:
          name: Run Gradle Build
          command: ./gradlew clean build
      - store_artifacts:
          path: build/libs